name: Swift Build
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Swift Build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: sw_vers
    - run: "ls -al /Applications/"
    - run: "system_profiler SPHardwareDataType"
    - run: "xcode-select -p"
    - run: "sudo xcode-select -p /Applications/Xcode.app"
