name: Greet Everybody
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on macOS
    runs-on: macos-latest
    steps:
    # This step prints the time.
    - run: echo "Hi"
    - run: sw_vers
