name: Swift Linux (Ubuntu 18.04)

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Swift Linux (Ubuntu 18.04)
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo lshw -short
    - run: sudo apt-get install inxi
    - run: inxi -F
